### ISSUE TITLE
CMB2 Tabs problem with CMB2-Post-Search-field

### ISSUE THREAD

**Issue by mlyczko** [rubengc/cmb2-tabs#8]
Hi

I have a problem:
I can't get working CMB2-Post-Search-field ( https://github.com/CMB2/CMB2-Post-Search-field ) with CMB2 Tabs.
When I add it "normally" it works fine but when I add this new field inside tabs I get simple input:
![2020-03-09_15h08_11](https://user-images.githubusercontent.com/17596117/76225092-4c7ba780-621c-11ea-9805-9eab8660df57.png)

Should I do something special to use custom fields inside CMB2 Tabs?

Best Regards
ML

**Comment by rubengc** [comment]
Hi @mlyczko 

My projects (GamiPress and AutomatorWP) uses CMB Tabs with lot of custom fields, so you error should come from another way
