### ISSUE TITLE
CMB2 Tabs not working for PHP 7.3.18

### ISSUE THREAD

**Issue by edwin243** [rubengc/cmb2-tabs#9]
Hi: cmb2 tabs not working in php 7.3.18. The first that was wrong was the cmb2-tabs.php is not found because the file name doesn't watch with the class name. I renamed the file name, to match the class nane but now I got an error at a line 249 in cmb2_base.php for the method below.
![Screenshot_20200720-030025](https://user-images.githubusercontent.com/15739366/87925681-7e581280-ca35-11ea-9ad4-a5d0aa91cb76.png)

The error is array to string conversion.

**Comment by rubengc** [comment]
Hi @edwin243 

I have PHP 8 installed and I'm not facing this issue, have you checked that you have correctly defined you tabs?

**Comment by edwin243** [comment]
Sorry,there wasn't anything wrong with the plug-in. Some files were
missing. Probably they became corrupted.
